# Generated by Django 4.2.6 on 2023-11-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_patata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patata',
        ),
    ]
