# Generated by Django 4.2.8 on 2024-01-20 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='name',
        ),
        migrations.AddField(
            model_name='therapist',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
